
CREATE TABLE lists
(
	list_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
	list_name text not null
);

CREATE TABLE cards
(
    list_id INTEGER REFERENCES lists(list_id),
    card_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
    company_name TEXT NOT NULL,
    position_applied TEXT NOT NULL,
    job_location TEXT,
    job_url TEXT,
    job_description TEXT
);
